name: Auto Publish on Main Merge

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to analyze commit history

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://npm.pkg.github.com'

      - name: Determine version bump and publish ESLint plugin
        id: publish-eslint
        working-directory: ./eslint-plugin-brand-detector
        run: |
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PAT }}

      - name: Determine version bump and publish Stylelint plugin
        id: publish-stylelint
        working-directory: ./stylelint-plugin-brand-detector
        run: |
          npm install
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_PAT }}